### ISSUE TITLE
Make Error at CMakeLists.txt When test the go samples

### ISSUE THREAD

**Issue by knight-hjh** [edgelesssys/edgelessrt#110]
I followed the document here:
![image](https://user-images.githubusercontent.com/38315608/172085284-e3752bcb-6342-422a-aed3-2195b83e175f.png)
and when I execute cmake .. under the build. it will report the error:
CMake Error at CMakeLists.txt:17 (add_executable):
  Target "enclave" links to target "openenclave::ertdeventry" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
![image](https://user-images.githubusercontent.com/38315608/172085392-291e1c6d-d6a7-4a56-986f-0990d2db46c6.png)

 I have checked the CmakeList.
![image](https://user-images.githubusercontent.com/38315608/172085424-df7f8c38-a5df-4211-835b-8ca8cdf0c3ac.png)
target_link_libraries(enclave openenclave::oeenclave openenclave::ertdeventry
                      ${CMAKE_BINARY_DIR}/hello.a)
This command requires to link the openenclave:;ertdeventry. but when I checked the file under openenclave/cmake, it shows like that 
![image](https://user-images.githubusercontent.com/38315608/172085568-4066084e-54b9-43d9-8be9-6d8c37a096ca.png)
there is no openenclave::ertdeventry. 

anyone knows?  :(

**Comment by thomasten** [comment]
Can you show the output of `echo $CMAKE_PREFIX_PATH` ?

**Comment by knight-hjh** [comment]
![image](https://user-images.githubusercontent.com/38315608/172269487-e9334ea7-3e50-44da-9241-dc0cba190bf4.png)
Is that right?

**Comment by knight-hjh** [comment]
thanks, it works now.
