### ISSUE TITLE
OE_PLATFORM_ERROR

### ISSUE THREAD

**Issue by knight-hjh** [edgelesssys/edgelessrt#111]
when I test the sample remote_attestation. it report the error.
![image](https://user-images.githubusercontent.com/38315608/172386023-d5138107-bcb3-416d-b762-689564b1afc2.png)
do you know how to fix it?

**Comment by knight-hjh** [comment]
![image](https://user-images.githubusercontent.com/38315608/172744602-a2914318-ce40-4bbd-b7cb-8576a58e4f6f.png)
This is the output of the command.

**Comment by thomasten** [comment]
Do you have a [PCCS](https://docs.edgeless.systems/ego/#/reference/attest) running? Have you set pccs_url in /etc/sgx_default_qcnl.conf accordingly?

**Comment by knight-hjh** [comment]
![image](https://user-images.githubusercontent.com/38315608/172819543-f476e8fe-85e5-4d2d-a6fe-575cfe2a662a.png)
I have tried to run PCCS use `docker run -e APIKEY=<your-API-key> -p 8081:8081 --name pccs -d ghcr.io/edgelesssys/pccs`.
But the error still there.
I think I have run the PCCS locally. Do I still need to modify that file?
![image](https://user-images.githubusercontent.com/38315608/172819901-04ef6155-d47e-48df-9f39-faa4580c3db1.png)

**Comment by thomasten** [comment]
try setting `use_secure_cert` to `false`

**Comment by knight-hjh** [comment]
it works now. but when I run `sudo go run client.go -s `/opt/edgelessrt/bin/oesign signerid -k build/public.pem`
it report the error:
![image](https://user-images.githubusercontent.com/38315608/172823606-5155fee5-97de-4e4f-9dff-98557848696b.png)
In EGO, it use the command 'CGO_CFLAGS=-I/opt/ego/include CGO_LDFLAGS=-L/opt/ego/lib' to solve this problem. but i can't find  the `openenclave/attestation/verifier.h`

**Comment by knight-hjh** [comment]
yeah, the command `. /opt/edgelessrt/share/openenclave/openenclaverc` is useful here to solve this problem. 
but when i run the client. it report:
![image](https://user-images.githubusercontent.com/38315608/172845108-8e276f70-aef5-4837-82d1-20d9a109e4cf.png)

**Comment by knight-hjh** [comment]
Hahahaha, a little embarrassed, I forgot to ask this question in EGO before.
As for why EdgelessRT,  because I first discovered this software. In the process, I found that this actually used EGO. So I want to know more about EdgelessRT and think about why there is EdgelessRT after EGO.

**Comment by knight-hjh** [comment]
I have been misunderstanding it before. I really feel that EGO is better to use. I will user more specifically later. Thank you very much for your patient answer these days. Finally, ask if there is a place for learners to communicate about this project.

**Comment by knight-hjh** [comment]
Thanks a lot. :)
