### ISSUE TITLE
Report Security Vulnerabilities

### ISSUE THREAD

**Issue by qinkunbao** [edgelesssys/edgelessrt#46]
Hello,

I might find some security vulnerabilities in edgelessrt. Is edgelessrt a production-ready SGX SDK? Is there any way that I can report security-related problems to you?

**Comment by thomasten** [comment]
Hi @qinkunbao,

Thanks for bringing this up! You can report to security@edgeless.systems
We will also add this reporting practice to our docs.

**Comment by qinkunbao** [comment]
Thank you!
