### ISSUE TITLE
How can I modify the enclave.conf to change the maximum thread count or other SGX parameters?

### ISSUE THREAD

**Issue by kunmel-0** [edgelesssys/edgelessrt#87]
Hi,  I want to change the max number of hreads/processes when I run the project, but I don't know what parameter should I add to the enclave.conf, please give me some help. And is there any related documents? So I can do my own research.

**Comment by thomasten** [comment]
Hi, `NumTCS` is the number of threads. Doc is here https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/buildandsign.md#signing-an-sgx-enclave
