### ISSUE TITLE
What are the design and implementation principles of  edgelessrt

### ISSUE THREAD

**Issue by bronzeMe** [edgelesssys/edgelessrt#96]
Hi, "Edgeless RT is an SDK for Trusted Execution Environments (TEE) built on top of Open Enclave."
It also looks like a libos, because it supports Go/C/C++/Rust apps, how does edgelessrt do it?

So, what is the differences between edgelessrt and ego? 

Are there any documents showing the design principles of edgelessrt or ego?

Thanks.

**Comment by thomasten** [comment]
Hi @bronzeMe,

You can think of Edgeless RT as Open Enclave with many more POSIX functions and syscalls implemented. In this regard, it's similar to a libos. On the other hand, you must recompile the application and it must be fully statically linked. Primary advantage compared to a libos is a smaller TCB. Disadvantages are more effort and less compatibility with existing apps.

Go and experimental Rust support are achieved by compiling the Go/Rust code to a static library and linking it to a C/C++ project (which can be a stub).

As this can be quite cumbersome, we created EGo. While the inner workings are similar, EGo hides most of this from the user and offers a workflow that is very similar to the usual Go workflow.

You can find some notes about its principles on these pages:
https://docs.edgeless.systems/ego
https://docs.edgeless.systems/ego/#/knowledge/model

**Comment by bronzeMe** [comment]
@thomasten , thank you so much, it's helpful .

**Comment by bronzeMe** [comment]
Hi， @thomasten ， by the way, does EdgelessRT support run a native C app without any modification to this C app?

**Comment by thomasten** [comment]
It depends. As for the other languages, you must at least recompile and fully statically link the C app. Some syscalls are missing (e.g., everything around fork/exec), some are limited in functionality (like mmap).

As an example, for https://github.com/edgelesssys/edgelessdb we run MariaDB and RocksDB with Edgeless RT. We did modify them a bit, but mostly for I/O security and not compatibility. (In particular, Edgeless RT doesn't have automatic file encryption.)
